Add Get-ClientLicense function
CommvaultEngg/CVPowershellSDK pull request #9
Opened 2020-02-21 15:06 UTC by CraigTolley

Hi,

Have added a new function to specifically get the client licenses. Am working on a counter function to remove client licenses as well.

Hope format is ok. Tried to keep with everything that you have already done. 

Craig

2020-02-21 16:22 UTC, CraigTolley commented
#4

2020-02-24 14:47 UTC, gstoops commented on Modules/Commvault.CommCell/Commvault.CommCell.psm1
> +    [CmdletBinding(DefaultParameterSetName = 'Default')]
default should be 'ByName'

2020-02-24 14:48 UTC, gstoops commented on Modules/Commvault.CommCell/Commvault.CommCell.psm1
> +        [Parameter(Mandatory = $False, ParameterSetName = 'ByName')]
[Parameter(Mandatory = $True, ParameterSetName = 'ByName', ValueFromPipeline = $True, ValueFromPipelineByPropertyName = $True)]

2020-02-24 14:48 UTC, gstoops commented on Modules/Commvault.CommCell/Commvault.CommCell.psm1
> +        [Parameter(Mandatory = $False, ParameterSetName = 'ById')]
[Parameter(Mandatory = $True, ParameterSetName = 'ByName', ValueFromPipeline = $True, ValueFromPipelineByPropertyName = $True)]

2020-02-24 14:48 UTC, gstoops commented on Modules/Commvault.CommCell/Commvault.CommCell.psm1
> +            }
Delete these lines.

2020-02-24 14:49 UTC, gstoops commented on Modules/Commvault.CommCell/Commvault.CommCell.psm1
> +            }
if ($PSCmdlet.ParameterSetName -eq 'ByName') {
                $clientObj = (Get-CVClient -Name $Name)
                if ($null -ne $clientObj) {
                    $Id = $clientObj.clientId
                }
                else {
                    Write-Information -InformationAction Continue -MessageData "INFO: $($MyInvocation.MyCommand): client not found having name [$Name]"
                    return
                }
            }

2020-02-24 14:49 UTC, gstoops commented on Modules/Commvault.CommCell/Commvault.CommCell.psm1
> +            $headerObj = Get-CVRESTHeader $sessionObj
please add blank line here.

2020-02-24 14:51 UTC, gstoops commented on Modules/Commvault.CommCell/Commvault.CommCell.psm1
> +            }
if ($response.IsValid) {
                Write-Output $response.Content.licensesInfo
            }
            else {
                Write-Information -InformationAction Continue -MessageData "INFO: $($MyInvocation.MyCommand): license information not found for client Id [$Id]"
            }

2020-02-24 14:51 UTC, gstoops commented on Modules/Commvault.CommCell/Commvault.CommCell.psm1
> +        $LicensesToRelease
What type is this?

2020-02-24 14:52 UTC, gstoops commented on Modules/Commvault.CommCell/Commvault.CommCell.psm1
> +        [Alias('ClientName')]
The $Name and $Id params here should be coded identical to the Get function

2020-02-24 14:54 UTC, gstoops commented on Modules/Commvault.CommCell/Commvault.CommCell.psm1
> +    Param (
[CmdletBinding(DefaultParameterSetName = 'ByName', SupportsShouldProcess = $True, ConfirmImpact = 'High')]

2020-02-24 14:55 UTC, gstoops commented on Modules/Commvault.RESTSession/Commvault.RESTSession.psm1
>              'Add-CVClientGroup' = @{
Please add blank line here.

2020-02-24 14:57 UTC, gstoops requested changes
Hi Craig, great work here. We just need to address a few things. :)
Please push your changes to Commvault.CommCell.psd1 for the new function exports:
FunctionsToExport = @('Get-CVAlert', 'Get-CVClientGroup', 'Get-CVClient', 'Get-CVClientLicense', 'Revoke-CVClientLicense',
                      'Get-CVSubclient', 'Get-CVVersionInfo', 'Set-CVClient', 'Set-CVClientGroup')

2020-02-24 21:54 UTC, CraigTolley commented
All suggestions incorporated.

2020-03-26 11:53 UTC, CraigTolley commented
Is there anything else that you need me to do before this can get merged in?

2020-03-27 09:37 UTC, closed without merging

2020-03-27 09:38 UTC, CraigTolley commented
Closed as updating my repos and creating a new PR